[package]
name = "raw_nbits_vec"
version = "0.1.0"
authors = ["Huo Linhe <huolinhe@berrygenomics.com>"]

[dependencies]
num = "0.1.28"

[dependencies.clippy]
version = "0.0.30"
optional = true

[features]
default = []
dev = ["clippy"]
